### ISSUE TITLE
geojson?

### ISSUE THREAD

**Issue by kpennell** [clementallen/react-leaflet-textpath#10]
Is it possible to use this with react-leaflet geojson? Have the linestrings be labeled?

**Comment by clementallen** [comment]
I've not used geojson with react-leaflet before so I couldn't tell you I'm afraid.  Also, this library is just a wrapper around the [leaflet-textpath](https://github.com/makinacorpus/Leaflet.TextPath) library so this package should (hopefully!) do everything it can do.  I've taken a quick look there and there is no mention of geojson support.

However, if you do find a way of making it work, a PR or comment would be more than welcome!

**Comment by kpennell** [comment]
Will do, thank you.
