### ISSUE TITLE
Does not work within a <Pane/> element with `name` parameter set

### ISSUE THREAD

**Issue by nemosmithasf** [clementallen/react-leaflet-textpath#52]
The element throws an error when placed a <Pane /> element (but not when directly as a child to <MapContainer />)

See below for error:

![Screen Shot 2021-02-04 at 7 09 52 PM](https://user-images.githubusercontent.com/14184529/106971391-d5e17580-671c-11eb-951f-31b34c3147ac.png)

**Comment by clementallen** [comment]
Hi @nemosmithasf 

Can you please share a codesandbox which replicates this issue?  It will help me more easily understand and debug it.

Here's a template that may help: https://codesandbox.io/s/react-leaflet-textpath-hps8j

**Comment by nemosmithasf** [comment]
Here you go: https://codesandbox.io/s/react-leaflet-textpath-forked-ku7q4?file=/src/index.js:489-507

It seems like its not `<Pane/>` that is the problem, its the `name` parameter

**Comment by clementallen** [comment]
Thanks for the very useful codesandbox!

I've done some investigation and it unfortunately looks to be an issue with the underlying Leaflet.TextPath library not supporting Panes.  The library is fairly old and not seen active development for a while so is unlikely to be fixed there anytime soon.

Here are some issues I found relating to this problem in their repo:

makinacorpus/Leaflet.TextPath#83
makinacorpus/Leaflet.TextPath#69
makinacorpus/Leaflet.TextPath#45

**Comment by nemosmithasf** [comment]
I see, that's a shame. Thanks for looking into it.
